create database javaapplications;

use javaapplications;

CREATE TABLE
USERS (
USER_ID INT AUTO_INCREMENT ,
USER_NAME VARCHAR(25),
FIRST_NAME VARCHAR(50),
LAST_NAME VARCHAR(50),
ADDRESS_LINE VARCHAR(50),
CITY VARCHAR(20),
STATE VARCHAR(20),
PIN_CODE INT,
MOBILE_NUMBER VARCHAR(10),
EMAIL_ID VARCHAR(50),
CREATED_DATE DATETIME,
PRIMARY KEY (USER_ID)
);